# Theme Definitions

[DARK]
Foreground=White
Background=Black
Header=Cyan
Clock=Green
Date=Yellow
Status=White
Error=Red

[LIGHT]
Foreground=Black
Background=White
Header=Blue
Clock=Red
Date=DarkBlue
Status=DarkGray
Error=Red